### ISSUE TITLE
Why APA?

### ISSUE THREAD

**Issue by AlexFundorin** [RoboticsBrno/SmartLeds#16]
I 'm not using apa method, just an single led connection with 3 "+ data -" wires. 
Yet, there are some errors on compilation.

**Comment by yaqwsx** [comment]
It is a bug that was recently fixed (3f66629b49f75d6eda0feb2b8ac513e396440b65), however, my colleague forgot to increase the version number and therefore, the fix was not propagated to the repository. I have increased the version number, but it can take up to 24 hours to propagate in the repository.

Meanwhile, you can add `git@github.com:RoboticsBrno/SmartLeds.git` instead of `SmartLeds` in your platformio.ini as a dependency.

**Comment by yaqwsx** [comment]
The fix already present in the repository. Please confirm it works.

**Comment by AlexFundorin** [comment]
I can partially confirm, since I've DL the repository, instead of adding some extra lines to the ini file.
So, the errors are disappeared. Yet, I couldn't test the lib itself since it was a surprise for me that my led board is only working with 5V logic, while I'm using 3V3 board in my current project.

**Comment by yaqwsx** [comment]
WS2812 indeed require at least 5V power supply and unreliably work with 3.3V logic signals.
